<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>logo.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Img\logo.ico" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="logo.ico" />
    <Content Include="Resources\Img\logo.ico">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="HandyControl" Version="3.5.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Binder" Version="10.0.7" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="10.0.7" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Prism.DryIoc" Version="9.0.537" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="10.0.0" />
    <PackageReference Include="Serilog.Sinks.Async" Version="2.1.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="7.0.0" />
    <PackageReference Include="Serilog.Sinks.OpenObserve-KKP" Version="1.0.6" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeviceControl.Core\DeviceControl.Core.csproj" />
    <ProjectReference Include="..\DeviceControl.Data\DeviceControl.Data.csproj" />
    <ProjectReference Include="..\DeviceControl.WebHost\DeviceControl.WebHost.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.extend.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
